export const isDemoBypassEnabled = () =>
  process.env.NODE_ENV === 'development' || process.env.NEXT_PUBLIC_EXPOSE_INTERNALS === 'true';

export const demoUser = {
  username: 'demo-user',
};

export const demoUserAttributes = {
  email: 'demo@anystore.local',
  given_name: 'Demo',
  family_name: 'User',
};

export const demoPermissionDetails = {
  allAccess: true,
  canAccessAuditLogsPanel: false,
  canAccessDiligenceDashboard: true,
  canAccessIssuesPanel: true,
  canAccessQuestionairePanel: true,
  canAccessUserManagementPanel: false,
  canAddQuestionaire: true,
  canAnswerIssue: true,
  canCreateDiligenceWidget: true,
  canCreateIssue: true,
  canCreatePermissionGroups: false,
  canDeleteDataroom: true,
  canDeleteWidgets: true,
  canExportAuditLogs: false,
  canInviteUsers: ['*'],
  canMoveWidgets: true,
  canOrganize: true,
  canQueryEntireDataroom: true,
  canRemovePeerPermission: false,
  canRemoveUsers: [],
  canRetryProcessing: true,
  canUpdatePeerPermissions: false,
  canUpdateUserPermissions: [],
  canViewAuditLogs: false,
  canViewPermissionGroupDetails: false,
  canViewUsers: false,
  dataroomId: 'anystore',
  defaultFilePerms: {
    viewAccess: true,
    watermarkContent: false,
    deleteAccess: true,
    editAccess: true,
    viewComments: true,
  },
  defaultFolderPerms: {
    allowUploads: true,
    createFolders: true,
    addComments: true,
    viewComments: true,
    viewContents: true,
  },
  id: 'demo-permissions',
  name: 'Owner',
  role: 'OWNER',
  sharedBy: 'demo@anystore.local',
};

export const demoDatarooms = [
  {
    id: 'anystore',
    title: 'My Anystore',
    bucketName: 'My Anystore',
    uuid: 'anystore',
    permissionLevel: 'OWNER',
    sharedBy: 'demo@anystore.local',
    addedAt: new Date().toISOString(),
    lastOpened: 'Just now',
    status: 'READY',
    users: [
      {
        email: 'demo@anystore.local',
        name: 'Demo User',
        role: 'Owner',
      },
    ],
  },
];

const now = new Date();
const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const lastWeek = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

export const demoFileNodes = [
  {
    id: 'folder-life',
    name: 'Life admin',
    uploadedBy: 'Demo User',
    type: 'folder',
    size: ' ',
    isFolder: true,
    createByEmail: 'demo@anystore.local',
    createByName: 'Demo User',
    lastModified: now.toISOString(),
    tags: null,
    summary: '',
    status: 'COMPLETED',
    parentId: 'ROOT',
  },
  {
    id: 'receipt-target',
    name: 'target-receipt-kitchen-supplies.pdf',
    uploadedBy: 'Demo User',
    type: 'file',
    size: '428 KB',
    isFolder: false,
    createByEmail: 'demo@anystore.local',
    createByName: 'Demo User',
    lastModified: now.toISOString(),
    tags: {
      document_type: 'Receipt',
      relevant_project: 'Home',
      involved_parties: ['Target'],
      key_topics: ['Kitchen', 'Supplies', 'Returns'],
      dates: [{ date: '2026-06-01', type: 'purchase', description: 'Purchase date' }],
      deal_phase: 'Personal',
      confidentiality: 'Private',
    },
    summary: 'A household receipt for kitchen supplies and storage bins from Target.',
    status: 'COMPLETED',
    parentId: 'ROOT',
  },
  {
    id: 'lease-pdf',
    name: 'apartment-lease-renewal.pdf',
    uploadedBy: 'Demo User',
    type: 'file',
    size: '1.2 MB',
    isFolder: false,
    createByEmail: 'demo@anystore.local',
    createByName: 'Demo User',
    lastModified: yesterday.toISOString(),
    tags: {
      document_type: 'Lease',
      relevant_project: 'Apartment',
      involved_parties: ['Property Manager'],
      key_topics: ['Rent', 'Renewal', 'Move-out'],
      dates: [{ date: '2026-08-31', type: 'deadline', description: 'Renewal deadline' }],
      deal_phase: 'Personal',
      confidentiality: 'Private',
    },
    summary: 'Lease renewal packet with renewal deadline, rent amount, and move-out instructions.',
    status: 'COMPLETED',
    parentId: 'ROOT',
  },
  {
    id: 'gift-screenshot',
    name: 'gift-idea-blue-sneakers.png',
    uploadedBy: 'Demo User',
    type: 'file',
    size: '934 KB',
    isFolder: false,
    createByEmail: 'demo@anystore.local',
    createByName: 'Demo User',
    lastModified: lastWeek.toISOString(),
    tags: {
      document_type: 'Screenshot',
      relevant_project: 'Gift ideas',
      involved_parties: [],
      key_topics: ['Birthday', 'Shoes', 'Blue'],
      dates: [],
      deal_phase: 'Saved',
      confidentiality: 'Private',
    },
    summary: 'Screenshot of a blue sneaker gift idea saved for later.',
    status: 'COMPLETED',
    parentId: 'ROOT',
  },
  {
    id: 'warranty-doc',
    name: 'airpods-warranty-info.docx',
    uploadedBy: 'Demo User',
    type: 'file',
    size: '212 KB',
    isFolder: false,
    createByEmail: 'demo@anystore.local',
    createByName: 'Demo User',
    lastModified: new Date('2026-05-30T15:00:00.000Z').toISOString(),
    tags: {
      document_type: 'Warranty',
      relevant_project: 'Electronics',
      involved_parties: ['Apple'],
      key_topics: ['Warranty', 'Support', 'Serial number'],
      dates: [{ date: '2027-05-30', type: 'expiration', description: 'Warranty end' }],
      deal_phase: 'Personal',
      confidentiality: 'Private',
    },
    summary: 'Warranty information and serial number for AirPods.',
    status: 'COMPLETED',
    parentId: 'ROOT',
  },
];

export const demoSearchableFiles = demoFileNodes
  .filter((item) => !item.isFolder)
  .map((item) => ({
    fileId: item.id,
    fileName: item.name,
    fullPath: `My Anystore/${item.name}`,
    parentFolderId: item.parentId,
    parentFolderName: 'Home',
    size: item.size,
    batchStatus: item.status,
    contentType: item.name.endsWith('.png') ? 'image/png' : 'application/pdf',
    documentSummary: item.summary,
    documentTitle: item.name,
    id: item.id,
    lastModified: item.lastModified,
    name: item.name,
    tags: JSON.stringify(item.tags),
    tagsList: item.tags ? item.tags.key_topics.join(', ') : '',
    uploadedBy: item.uploadedBy,
    uploadedByEmail: item.createByEmail,
    isFolder: false,
  }));
